name: Delete SauceLabs Errored Jobs

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 02:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  delete-errored-jobs:
    runs-on: windows-latest

        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Verify script exists
        shell: pwsh
        run: |
          if (!(Test-Path "./Delete-AllErroredSauceJobs.ps1")) {
            Write-Error "Script not found!"
            exit 1
          }

      - name: Run deletion script
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process Bypass
          $from = (Get-Date).AddDays(-1).ToString("yyyy-MM-dd")
          ./Delete-AllErroredSauceJobs.ps1 -From $from