name: NUnit Only

on:
  push:
    paths:
      - '.github/workflows/nunit-pipeline.yml'
      - 'Saucery/**'
      - 'Merlin.NUnit/**'
      - 'Merlin.NUnit.RealDevices/**'
    branches:
      - master
      - 'dependabot/**'
      - 'releases/**'
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - 'test/**'
      - 'bug/**'
  workflow_dispatch:

env:
  PROJECT_NAME: Saucery
  SOLN_FILE: Saucery.sln                                                                        # full path to your solution file
  COVERLET_DIR: ./TestResults
  NUNIT_INT_DIR: Merlin.NUnit
  NUNIT_RD_INT_DIR: Merlin.NUnit.RealDevices

  UT_PROJECT: Saucery.Core.Tests/Saucery.Core.Tests.csproj                                      # full path to your unit test project file
  TT_PROJECT: Template.Tests/Template.Tests.csproj
  
  M_NUNIT_PROJECT: Merlin.NUnit/Merlin.NUnit.csproj                                             # full path to nunit internal integration test project file
  M_RD_NUNIT_PROJECT: Merlin.NUnit.RealDevices/Merlin.NUnit.RealDevices.csproj                  # full path to nunit internal real device integration test project file
  
  SAUCE_USER_NAME: ${{ secrets.SAUCE_USER_NAME }}
  SAUCE_API_KEY: ${{ secrets.SAUCE_API_KEY }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  CONFIG: Release
  APP_PACKAGE_PATH: 'published'                                                                 # set this to the path to your web app project, defaults to the repository root
  COVERAGE_FORMAT: cobertura
  UNIT_COVERAGE_FILENAME: opencover.unit.xml
  NUNIT_INTEGRATION_COVERAGE_FILENAME: opencover.nunit.integration.xml
  NUNIT_RD_INTEGRATION_COVERAGE_FILENAME: opencover.nunit.realdevice.integration.xml
  COVERAGE_THRESHOLD: 80

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        # Check for latest at link at .NET 9 download page (https://dotnet.microsoft.com/download/dotnet/9.0)
        dotnet-version: 9.0.x

    - name: Compile solution
      run: dotnet build -c ${{ env.CONFIG }}

    - name: Run TUnit Unit tests (with coverage + TRX)
      run: |
       dotnet run -c ${{ env.CONFIG }} --project ${{ env.UT_PROJECT }} -- \
       --report-trx \
       --report-trx-filename "unit.trx" \
       --coverage \
       --coverage-output "${{ github.workspace }}/${{ env.COVERLET_DIR }}/${{ env.UNIT_COVERAGE_FILENAME }}" \
       --coverage-output-format "${{ env.COVERAGE_FORMAT }}" \
       --results-directory "TestResults"

    - name: Run Template Tests
      run: dotnet test -c ${{ env.CONFIG }} ${{ env.TT_PROJECT }}

    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload TRX
      uses: actions/upload-artifact@v5
      with:
        name: unit-test-trx
        path: ${{ env.COVERLET_DIR }}/unit.trx

    - name: Publish Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: unit-test-results
        path: ${{ env.COVERLET_DIR }}/${{env.UNIT_COVERAGE_FILENAME}}

  nunit-integration-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        # Check for latest at link at .NET 9 download page (https://dotnet.microsoft.com/download/dotnet/9.0)
        dotnet-version: 9.0.x
    
    - name: Compile solution
      run: dotnet build -c ${{ env.CONFIG }}

    - name: Run NUnit Integration Tests
      uses: b3b00/coverlet-action@1.3.5-alpha2
      with:
        testProject: ${{ env.M_NUNIT_PROJECT }}
        output: ${{ env.NUNIT_INTEGRATION_COVERAGE_FILENAME }}
        outputFormat: ${{ env.COVERAGE_FORMAT }}
        #threshold: ${{ env.COVERAGE_THRESHOLD }}
        excludes: '[Merlin.NUnit]Tests.*'

    - name: Display structure of downloaded files
      run: ls -R

    - name: Publish Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: nunit-integration-test-results
        path: ${{ env.COVERLET_DIR }}/${{env.NUNIT_INTEGRATION_COVERAGE_FILENAME}}

  nunit-real-integration-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        # Check for latest at link at .NET 9 download page (https://dotnet.microsoft.com/download/dotnet/9.0)
        dotnet-version: 9.0.x
    
    - name: Compile solution
      run: dotnet build -c ${{ env.CONFIG }}

    - name: Run NUnit Integration Tests
      uses: b3b00/coverlet-action@1.3.5-alpha2
      with:
        testProject: ${{ env.M_RD_NUNIT_PROJECT }}
        output: ${{ env.NUNIT_RD_INTEGRATION_COVERAGE_FILENAME }}
        outputFormat: ${{ env.COVERAGE_FORMAT }}
        #threshold: ${{ env.COVERAGE_THRESHOLD }}
        excludes: '[Merlin.NUnit.RealDevices]Tests.*'

    - name: Display structure of downloaded files
      run: ls -R

    - name: Publish Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: nunit-real-integration-test-results
        path: ${{ env.COVERLET_DIR }}/${{env.NUNIT_RD_INTEGRATION_COVERAGE_FILENAME}}

  generate-report:
    runs-on: ubuntu-latest
    needs: [nunit-integration-tests,
            nunit-real-integration-tests]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Download unit-test results
      uses: actions/download-artifact@v5
      with:
        name: unit-test-results

    - name: Download nunit-integration-test results
      uses: actions/download-artifact@v5
      with:
        name: nunit-integration-test-results

    - name: Download nunit-real-integration-test results
      uses: actions/download-artifact@v5
      with:
        name: nunit-real-integration-test-results
    
    # - name: Present working directory
    #   run: pwd

    # - name: Display structure of downloaded files
    #   run: ls -R

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.18
      with:
        # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        reports: ${{env.UNIT_COVERAGE_FILENAME}};${{env.NUNIT_INTEGRATION_COVERAGE_FILENAME}};${{env.NUNIT_RD_INTEGRATION_COVERAGE_FILENAME}}
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'HtmlInline;Cobertura' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v5
      with:
        name: CoverageReport # Artifact name        
        path: coveragereport # Directory containing files to upload
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}