name: Build Pipeline

on:
  push:
    branches:
      - master

env:
  SOLN_FILE: Saucery.sln               # set this to your application's name
  CONFIG: Release
  APP_PACKAGE_PATH: 'published'        # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.401' # Check for latest at link at .NET 5 download page (https://dotnet.microsoft.com/download/dotnet/5.0)
    - run: dotnet build
    - run: dotnet test