name: publish saucery.core to nuget
on: 
    workflow_dispatch:

env:
  PROJECT_NAME: Saucery.Core
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  CONFIG: Release
  NUPKG_DIR: out
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      - name: Pack NuGet package
        run: dotnet pack -c ${{ env.CONFIG }} ${{ env.PROJECT_NAME }}\${{ env.PROJECT_NAME }}.csproj -o ${{ env.NUPKG_DIR }}
      - name: Push generated package to NuGet
        run: dotnet nuget push ${{ env.NUPKG_DIR }}\*.nupkg -Source '${{ NUGET_SOURCE }}' --api-key ${{ env.NUGET_API_KEY }}