name: Publish Saucery.XUnit3 to NuGet

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_NAME: Saucery.XUnit3
  PROJECT_PATH: Saucery.XUnit3/Saucery.XUnit3.csproj
  PACKAGE_ID: Saucery.XUnit3
  CONFIG: Release
  NUPKG_DIR: out
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  DOTNET_VERSION: 10.0.x
  PUBLISH_MODE: local-version-newer
  BUILD_MODE: solution

jobs:
  publish:
    name: build, pack & publish Saucery.XUnit3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build, pack and publish package
        uses: ./.github/actions/publish-nuget-package
        with:
          project-path: ${{ env.PROJECT_PATH }}
          package-id: ${{ env.PACKAGE_ID }}
          configuration: ${{ env.CONFIG }}
          nupkg-dir: ${{ env.NUPKG_DIR }}
          nuget-source: ${{ env.NUGET_SOURCE }}
          nuget-api-key: ${{ env.NUGET_API_KEY }}
          publish-mode: ${{ env.PUBLISH_MODE }}
          build-mode: ${{ env.BUILD_MODE }}
