name: TUnit Only External

on:
  push:
    paths:
      - '.github/workflows/tunit-pipeline-external.yml'
      - 'ExternalMerlin.TUnit/**'
      - 'ExternalMerlin.TUnit.RealDevices/**'
    branches:
      - master
      - 'dependabot/**'
      - 'releases/**'
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - 'test/**'
      - 'bug/**'
  workflow_dispatch:

env:
  PROJECT_NAME: Saucery
  SOLN_FILE: Saucery.sln                                                                        # full path to your solution file
  EM_TUNIT_PROJECT: ExternalMerlin.TUnit/ExternalMerlin.TUnit.csproj                            # full path to tunit external integration test project file
  EM_RD_TUNIT_PROJECT: ExternalMerlin.TUnit.RealDevices/ExternalMerlin.TUnit.RealDevices.csproj # full path to tunit external integration test project file
  SAUCE_USER_NAME: ${{ secrets.SAUCE_USER_NAME }}
  SAUCE_API_KEY: ${{ secrets.SAUCE_API_KEY }}
  CONFIG: Release

permissions:
  contents: write

jobs:
  tunit-external-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        # Check for latest at link at .NET 9 download page (https://dotnet.microsoft.com/download/dotnet/9.0)
        dotnet-version: 9.0.x

    - name: Compile solution
      run: dotnet build -c ${{ env.CONFIG }}

    - name: Run External TUnit Integration Tests
      run: dotnet test -c ${{ env.CONFIG }} ${{ env.EM_TUNIT_PROJECT }} --no-build

  tunit-real-external-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        # Check for latest at link at .NET 9 download page (https://dotnet.microsoft.com/download/dotnet/9.0)
        dotnet-version: 9.0.x

    - name: Compile solution
      run: dotnet build -c ${{ env.CONFIG }}

    - name: Run External TUnit Real Integration Tests
      run: dotnet test -c ${{ env.CONFIG }} ${{ env.EM_RD_TUNIT_PROJECT }} --no-build

  tag:
    runs-on: ubuntu-latest
    needs: [tunit-external-tests,
            tunit-real-external-tests]
    steps:
    - name: Bump version and push tag
      if: ${{ (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && success() }}
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}