name: Unit Tests Only

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_NAME: Saucery
  SOLN_FILE: Saucery.sln
  COVERLET_DIR: ./TestResults

  UT_PROJECT: Saucery.Core.Tests.XUnitv3/Saucery.Core.Tests.XUnitv3.csproj
  TT_PROJECT: Template.Tests/Template.Tests.csproj


  CONFIG: Release
  APP_PACKAGE_PATH: 'published'
  COVERAGE_FORMAT: cobertura
  UNIT_COVERAGE_FILENAME: opencover.unit.xml
  COVERAGE_THRESHOLD: 80

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SAUCE_USER_NAME: ${{ secrets.SAUCE_USER_NAME }}
      SAUCE_API_KEY: ${{ secrets.SAUCE_API_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore solution
      run: dotnet restore

    - name: Compile solution
      run: dotnet build -c ${{ env.CONFIG }} --no-restore

    - name: Run xUnit v3 Unit tests with coverage
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "${{ github.workspace }}/${{ env.COVERLET_DIR }}"

        dotnet run -c ${{ env.CONFIG }} \
          --project ${{ env.UT_PROJECT }} -- \
          --coverage \
          --coverage-output-format "${{ env.COVERAGE_FORMAT }}" \
          --coverage-output "${{ env.UNIT_COVERAGE_FILENAME }}"
    
    - name: Enable Automated Test Report Artifact Upload
      uses: actions/github-script@v9
      with:
        script: |
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN']);
          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL']);

    - name: Run Template Tests
      run: dotnet run -c ${{ env.CONFIG }} --project ${{ env.TT_PROJECT }} --no-build

    - name: Publish Unit Test Results
      uses: actions/upload-artifact@v7
      with:
        name: unit-test-results
        path: Saucery.Core.Tests.XUnitv3/bin/${{ env.CONFIG }}/net10.0/TestResults/${{ env.UNIT_COVERAGE_FILENAME }}

  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Download unit-test results
      uses: actions/download-artifact@v8
      with:
        name: unit-test-results
        path: ${{ env.COVERLET_DIR }}

    - name: Present working directory
      run: pwd

    - name: Display structure of downloaded files
      run: ls -R

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.5.9
      with:
        reports: ${{ env.COVERLET_DIR }}/${{ env.UNIT_COVERAGE_FILENAME }}
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v7
      with:
        name: CoverageReport
        path: coveragereport
      if: ${{ always() }}

    - name: Bump version and push tag
      if: ${{ (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && success() }}
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}